### ISSUE TITLE
Thank you for doing this.

### ISSUE THREAD

**Issue by shotxxxx** [selfagency/nazi-detector#10]
Now I know which people on Twitter are the good guys. I hope you index 1000 more.

What? Did you really think echoes work on the goy as they work on the jew? You can label me anything you like, jew.
Which is what you are. You're a jew. You're jewish. A jewish jew.

**Comment by selfagency** [comment]
at least i'm not an anonymous coward who hides behind an animefapfest instead of having the courage to stand behind my convictions with my real identity

**Comment by shotxxxx** [comment]
Say what you wish. My point stands.

**Comment by selfagency** [comment]
the only point i see here is that you're racist scum who pretends to be proud of it but hides behind anonymity out of fear.

**Comment by shotxxxx** [comment]
My point is that you are creating useful database, and that you're a jew.

**Comment by selfagency** [comment]
do you think i hide the fact, in any way, shape, or form, that i'm a jewish person? google me for 10 seconds, shit for brains.

and yes, this will be a very useful database for mapping relationships between white supremacists and identifying key instigators.

**Comment by shotxxxx** [comment]
No, you're not hiding that you're a jew. But I still want to make a point that you are a jew. Jew.

**Comment by selfagency** [comment]
yea that's only upsetting if you think i'm ashamed of who i am. i'm not. ✡✡✡✡✡✡✡✡✡✡

**Comment by shotxxxx** [comment]
Always with the victim complex. Mind immediately jumping to persecution and suffering. I merely state what you are, jew. You are painting it as something "upsetting".
